# Generated by Django 5.1.4 on 2024-12-22 09:37

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoodLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('mood', models.CharField(choices=[('sad', 'Sad'), ('angry', 'Angry'), ('anxious', 'Anxious'), ('happy', 'Happy')], max_length=50)),
                ('note', models.TextField(blank=True, null=True)),
                ('task_rate', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='moodlog', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('on_happy', models.JSONField(default={'article': True, 'story': True, 'video': True})),
                ('on_sad', models.JSONField(default={'article': True, 'story': True, 'video': True})),
                ('on_angry', models.JSONField(default={'article': True, 'story': True, 'video': True})),
                ('on_anxious', models.JSONField(default={'article': True, 'story': True, 'video': True})),
                ('on_fear', models.JSONField(default={'article': True, 'story': True, 'video': True})),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('preference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.preference')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tasks', models.JSONField(default=dict)),
                ('rate', models.IntegerField(default=0)),
                ('date', models.DateField(default=datetime.date.today)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='task', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
