# Generated by Django 5.1.4 on 2025-02-03 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_task_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='converation',
            field=models.JSONField(default=list),
        ),
    ]
