# Generated by Django 5.1.4 on 2025-02-07 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_converation_profile_conversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.TextField(blank=True, null=True),
        ),
    ]
