# Generated by Django 5.1.4 on 2025-02-26 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_profile_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='country',
            field=models.TextField(blank=True, default='Country', null=True),
        ),
    ]
