# Generated by Django 5.1.4 on 2025-03-14 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_profile_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preference',
            name='on_happy',
        ),
        migrations.AlterField(
            model_name='preference',
            name='on_angry',
            field=models.JSONField(default={'Audio_based': True, 'Physical-Activities': True, 'Text-based': True, 'Visual-Based': True}),
        ),
        migrations.AlterField(
            model_name='preference',
            name='on_anxious',
            field=models.JSONField(default={'Audio_based': True, 'Physical-Activities': True, 'Text-based': True, 'Visual-Based': True}),
        ),
        migrations.AlterField(
            model_name='preference',
            name='on_fear',
            field=models.JSONField(default={'Audio_based': True, 'Physical-Activities': True, 'Text-based': True, 'Visual-Based': True}),
        ),
        migrations.AlterField(
            model_name='preference',
            name='on_sad',
            field=models.JSONField(default={'Audio_based': True, 'Physical-Activities': True, 'Text-based': True, 'Visual-Based': True}),
        ),
    ]
