# Generated by Django 5.1.4 on 2025-03-14 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_preference_on_happy_alter_preference_on_angry_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_reaction', models.TextField(max_length=30)),
                ('text', models.TextField(blank=True, null=True)),
                ('pair', models.JSONField(default=list)),
            ],
        ),
    ]
